name: CI Pipeline

on:
  push:
    branches:
      - setup/issue#7/ci-conda-automation
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniforge (Mambaforge)
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          miniforge-variant: Mambaforge
          use-mamba: true
          auto-update-conda: true
          environment-file: env.yml
          activate-environment: mle-dev

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate mle-dev
          conda install -y flake8 build

      - name: Run flake8 test
        shell: bash -l {0}
        run: |
          conda activate mle-dev
          flake8 src/mle_training/nonstandardcode.py

      - name: Build package
        shell: bash -l {0}
        run: |
          conda activate mle-dev
          python -m build  # Ensure build tools are installed

      - name: Show directory tree after build
        shell: bash -l {0}
        run: |
          tree dist/

      - name: Install built package
        shell: bash -l {0}
        run: |
          conda activate mle-dev
          pip install dist/*.whl

      - name: Run nonstandardcode.py
        shell: bash -c "source activate mle-dev && python -m mle_training.nonstandardcode"
