name: Testing Python Code

#on:
  #push:
    #branches:
      #- test/issue#11/pytest-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniforge (Mambaforge)
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          miniforge-variant: Mambaforge
          use-mamba: true
          auto-update-conda: true
          environment-file: env.yml
          activate-environment: mle-dev

      - name: Build the package
        run: python setup.py sdist bdist_wheel

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mle-training-package
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Setup Miniforge (Mambaforge)
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          miniforge-variant: Mambaforge
          use-mamba: true
          auto-update-conda: true
          environment-file: env.yml
          activate-environment: mle-dev

      - name: Download built package and test file
        uses: actions/download-artifact@v4
        with:
          name: mle-training-package
          path: dist/

      - name: Install package
        run: pip install dist/*.whl

      - name: Run tests with pytest
        run: pytest -v tests/test_package.py
