name: Unit Testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tree CLI
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Show directory structure before building
        run: tree -L 3

      - name: Setup Miniforge (Mambaforge)
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          miniforge-variant: Mambaforge
          use-mamba: true
          auto-update-conda: true
          environment-file: env.yml
          activate-environment: mle-dev

      - name: Install dependencies
        run: |
          conda install -y flake8 pytest
          pip install -e .

      - name: Run flake8 test
        run: flake8 src/main.py

      - name: Run tests with pytest
        run: pytest -v tests/

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel || { echo "Build failed"; exit 1; }
          ls -lh dist/

      - name: Verify package contents
        run: ls -lh dist/

      - name: Show directory structure after building
        run: tree -L 3

      - name: Package Conda and Environment
        run: tar -czvf miniforge-with-env.tar.gz /usr/share/miniconda3/

      - name: Upload build artifacts (Package + Conda + Script)
        uses: actions/upload-artifact@v4
        with:
          name: mle-training-package
          path: |
            dist/
            src/main.py
            miniforge-with-env.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Download built package and environment
        uses: actions/download-artifact@v4
        with:
          name: mle-training-package
          path: ./mle-training-package/

      - name: Verify downloaded artifacts
        run: tree ./mle-training-package/

      - name: Restore Miniforge and Conda Environment
        run: |
          sudo tar -xzvf ./mle-training-package/miniforge-with-env.tar.gz -C /
          echo "Conda environment and Miniforge restored."

      - name: Initialize Conda
        run: |
          . /usr/share/miniconda3/etc/profile.d/conda.sh
          conda activate mle-dev
          conda info --envs

      - name: Install package
        run: |
          . /usr/share/miniconda3/etc/profile.d/conda.sh
          conda activate mle-dev
          pip install ./mle-training-package/dist/*.whl

      - name: Run Modularized Code
        run: |
          . /usr/share/miniconda3/etc/profile.d/conda.sh
          conda activate mle-dev
          python ./mle-training-package/src/main.py
