name: ML Pipeline

on:
  push:
    branches:
      - enh/issue#17/add-ml-workflow
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tree CLI (for debugging)
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Show directory structure
        run: tree -L 3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          environment-file: env.yml
          activate-environment: mle-dev

      - name: Verify Python and Pytest
        run: |
          conda info --envs
          conda activate mle-dev
          which python
          python --version
          which pytest || echo "pytest not found"

      - name: Install dependencies
        run: |
          conda activate mle-dev
          pip install -e .

      - name: Run Unit Tests
        run: |
          conda activate mle-dev
          pytest tests/unit_tests/

  build:
    runs-on: ubuntu-latest
    needs: unit-test
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          environment-file: env.yml
          activate-environment: mle-dev

      - name: Verify Python and Pytest
        run: |
          conda info --envs
          conda activate mle-dev
          which python
          python --version
          which pytest || echo "pytest not found"

      - name: Build package
        run: |
          conda activate mle-dev
          python setup.py sdist bdist_wheel

      - name: Install package from wheel
        run: |
          conda activate mle-dev
          pip install dist/*.whl

      - name: Run Functional Tests
        run: |
          conda activate mle-dev
          pytest tests/functional_tests/

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mle-training-package
          path: dist/

      - name: Upload environment file
        uses: actions/upload-artifact@v4
        with:
          name: myenv-file
          path: env.yml

      - name: Upload scripts directory
        uses: actions/upload-artifact@v4
        with:
          name: scripts-folder
          path: scripts/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Download environment file
        uses: actions/download-artifact@v4
        with:
          name: myenv-file

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          environment-file: env.yml
          activate-environment: mle-dev

      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: mle-training-package
          path: dist/

      - name: Download scripts directory
        uses: actions/download-artifact@v4
        with:
          name: scripts-folder
          path: scripts/

      - name: Display directory structure (debugging)
        run: |
          conda activate mle-dev
          tree -L 3

      - name: Install package
        run: |
          conda activate mle-dev
          pip install dist/*.whl

      - name: Verify package installation
        run: |
          conda activate mle-dev
          python -c "import your_package; print('Package is installed successfully')"

      - name: Run ML scripts in help mode
        run: |
          conda activate mle-dev
          python scripts/ingest_data.py -h
          python scripts/train.py -h
          python scripts/score.py -h

      - name: Run ML scripts with error check
        run: |
          set -e  # Exit if any command fails
          conda activate mle-dev
          mkdir -p data models
          python scripts/ingest_data.py data/
          python scripts/train.py data/ models/
          python scripts/score.py models/ data/
