name: ML Pipeline

on:
  push:
    branches:
      - feat/issue#24/sklearn-pipeline-refactor
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tree CLI (for debugging)
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Show directory structure
        run: tree -L 3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          environment-file: env.yml
          activate-environment: mle-dev

      - name: Install dependencies
        run: |
          conda activate mle-dev
          pip install -e .

      - name: Run Unit Tests
        run: |
          conda activate mle-dev
          pytest tests/unit_tests/

  build:
    runs-on: ubuntu-latest
    needs: unit-test
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          environment-file: env.yml
          activate-environment: mle-dev

      - name: Build package
        run: |
          conda activate mle-dev
          python setup.py sdist bdist_wheel

      - name: Install package from wheel
        run: |
          conda activate mle-dev
          pip install dist/*.whl

      - name: Run Functional Tests
        run: |
          conda activate mle-dev
          pytest tests/functional_tests/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          environment-file: env.yml
          activate-environment: mle-dev

      - name: Display directory structure (for debugging)
        run: |
          conda activate mle-dev
          tree -L 3

      - name: Install package
        run: |
          conda activate mle-dev
          pip install dist/*.whl

      - name: Verify package installation
        run: |
          conda activate mle-dev
          python -c "import mle_training; print('Package is installed successfully')"

      - name: Run ML scripts with timestamped logging
        run: |
          conda activate mle-dev
          python scripts/ingest_data.py data/ --log-level INFO
          python scripts/train.py data/ models/ --log-level INFO
          python scripts/score.py models/ data/ --log-level INFO
